cookie:
  expiry_days: 30
  key: 1#78laksjhdd2020
  name: password_cookie
credentials:
  usernames:
    lakshmanb:
      email: akshan.ram4@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Lakshman Balasubramanian
      password: abc
pre-authorized:
  emails:
  - akshan.ram4@gmail.com
